	//All of the projectile definitions should go here
/*obj/Skills/Feva
	Blast
		verb
			fBlast()
				set category="Skills"
				Create_Projectile(usr,/obj/Projectiles/fevProjectile/Blast,Icon=sicon,Icon_State=sicon_state,)
	Charge
		verb
			fCharge()
				set category="Skills"
				Create_Projectile(usr,/obj/Projectiles/fevProjectile/Charge,Icon=sicon,Icon_State=sicon_state,)
	OmegaBlaster
		verb
			fOmega()
				set category="Skills"
				Create_Projectile(usr,/obj/Projectiles/fevProjectile/OmegaBlaster,Icon=sicon,Icon_State=sicon_state,)*/
//Use Create_Projectile() to spawn the proper projectile needed
//Currently, only blast uses the new
obj/Projectiles/fevProjectile
	Blast
		icon='Blasts.dmi'
		icon_state="1"
		Damage_Multiplier=1.5
		Deflectable=1
	Bullet
		icon='Bullet.dmi'
		icon_state=""
		Damage_Multiplier=1.25
		Offense_Multiplier=2
		Deflectable=1
	Charge
		icon='Blasts.dmi'
		icon_state="1"
		Damage_Multiplier=2.5
		Deflectable=1
		Explosive=1
		Explosion_Damage=2.5
	BusterBarrage
		icon='Blasts.dmi'
		icon_state="1"
		Damage_Multiplier=0.75
		Deflectable=1
		Explosive=0.5
		Explosion_Damage=0.75
	HellzoneGrenade
		icon='Blasts.dmi'
		icon_state="1"
		Damage_Multiplier=0.75
		Deflectable=1
		Explosive=1
		Explosion_Damage=0.75
		Homing=1
		Offense_Multiplier=2
		LifeTime=36
	OmegaBlaster
		icon='Blasts.dmi'
		icon_state="1"
		Damage_Multiplier=25
		MultiHit=50
		Knockback=1
		Deflectable=1
		Explosive=3
		Explosion_Damage=15
		LifeTime=320
	Ultima
		icon='Blasts.dmi'
		icon_state="1"
		Damage_Multiplier=50
		MultiHit=50
		Knockback=1
		Deflectable=0
		Explosive=5
		Explosion_Damage=15
	Hadouken
		Sekiha=1
		Damage_Multiplier=1.5
		MultiHit=5
		Knockback=1
		Deflectable=1